const { run, queryAll } = require('./index');

const SCHEMA = [
  `CREATE TABLE IF NOT EXISTS teams (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    display_name TEXT,
    abbreviation TEXT,
    league TEXT NOT NULL CHECK(league IN ('NBA', 'NFL')),
    conference TEXT,
    division TEXT,
    logo_url TEXT,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS games (
    id BIGINT PRIMARY KEY,
    league TEXT NOT NULL CHECK(league IN ('NBA', 'NFL')),
    home_team_id BIGINT,
    away_team_id BIGINT,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_score INTEGER DEFAULT 0,
    away_score INTEGER DEFAULT 0,
    status TEXT DEFAULT 'scheduled',
    period TEXT,
    game_date TEXT NOT NULL,
    venue TEXT,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    game_time TEXT,
    venue_city TEXT,
    venue_state TEXT,
    season_year INTEGER,
    season_type INTEGER,
    season_week INTEGER,
    broadcast TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS standings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league TEXT NOT NULL CHECK(league IN ('NBA', 'NFL')),
    team_id BIGINT,
    team TEXT NOT NULL,
    wins INTEGER DEFAULT 0,
    losses INTEGER DEFAULT 0,
    draws INTEGER DEFAULT 0,
    points_for INTEGER DEFAULT 0,
    points_against INTEGER DEFAULT 0,
    streak TEXT,
    conference_rank INTEGER,
    division_rank INTEGER,
    win_pct DOUBLE PRECISION DEFAULT 0,
    games_played INTEGER DEFAULT 0,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS sync_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league TEXT NOT NULL,
    status TEXT NOT NULL,
    message TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS nfl_schedule_weeks (
    season_year INTEGER NOT NULL,
    season_type INTEGER NOT NULL,
    season_week INTEGER NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    PRIMARY KEY (season_year, season_type, season_week)
  )`
];

const EXPECTED_TABLES = ['teams', 'games', 'standings', 'sync_log', 'nfl_schedule_weeks'];

async function ensureColumnsGame() {
  const gameColumns = [
    ['game_time', 'TEXT'],
    ['venue_city', 'TEXT'],
    ['venue_state', 'TEXT'],
    ['season_year', 'INTEGER'],
    ['season_type', 'INTEGER'],
    ['season_week', 'INTEGER'],
    ['broadcast', 'TEXT']
  ];

  const existing = await queryAll(
    `SELECT column_name FROM information_schema.columns WHERE table_name = 'games'`
  );
  const existingNames = new Set(existing.map(row => row.column_name));

  for (const [name, type] of gameColumns) {
    if (!existingNames.has(name)) {
      await run(`ALTER TABLE games ADD COLUMN ${name} ${type}`);
      console.log(`[Migrate] Coluna adicionada em games: ${name}`);
    }
  }
}

async function migrate() {
  console.log('[Migrate] Aplicando schema PostgreSQL...');
  for (const ddl of SCHEMA) {
    await run(ddl);
  }
  await ensureColumnsGame();
  console.log('[Migrate] Schema aplicado.');
}

async function validateTables() {
  const rows = await queryAll(
    `SELECT table_name FROM information_schema.tables
     WHERE table_schema = 'public'`
  );
  const existing = new Set(rows.map(row => row.table_name));
  const missing = EXPECTED_TABLES.filter(table => !existing.has(table));

  if (missing.length > 0) {
    throw new Error(`[Migrate] Tabelas ausentes no PostgreSQL: ${missing.join(', ')}`);
  }

  console.log('[Migrate] Tabelas validadas: ' + EXPECTED_TABLES.join(', '));
  return true;
}

async function runMigrations() {
  await migrate();
  await validateTables();
}

module.exports = { migrate, validateTables, runMigrations, EXPECTED_TABLES };

if (require.main === module) {
  runMigrations()
    .then(() => { console.log('[Migrate] Concluido com sucesso.'); process.exit(0); })
    .catch(err => { console.error('[Migrate] Falhou:', err.message); process.exit(1); });
}
