CREATE TABLE teams (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  display_name TEXT,
  abbreviation TEXT,
  league TEXT NOT NULL CHECK (league IN ('NBA', 'NFL')),
  conference TEXT,
  division TEXT,
  logo_url TEXT,
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE games (
  id INTEGER PRIMARY KEY,
  league TEXT NOT NULL CHECK (league IN ('NBA', 'NFL')),
  home_team_id INTEGER,
  away_team_id INTEGER,
  home_team TEXT NOT NULL,
  away_team TEXT NOT NULL,
  home_score INTEGER DEFAULT 0,
  away_score INTEGER DEFAULT 0,
  status TEXT DEFAULT 'scheduled',
  period TEXT,
  game_date TEXT NOT NULL,
  venue TEXT,
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  game_time TEXT,
  venue_city TEXT,
  venue_state TEXT,
  season_year INTEGER,
  season_type INTEGER,
  season_week INTEGER
);

CREATE TABLE nfl_schedule_weeks (
  season_year INTEGER NOT NULL,
  season_type INTEGER NOT NULL,
  season_week INTEGER NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  PRIMARY KEY (season_year, season_type, season_week)
);

CREATE TABLE standings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  league TEXT NOT NULL CHECK (league IN ('NBA', 'NFL')),
  team_id INTEGER,
  team TEXT NOT NULL,
  wins INTEGER DEFAULT 0,
  losses INTEGER DEFAULT 0,
  draws INTEGER DEFAULT 0,
  points_for INTEGER DEFAULT 0,
  points_against INTEGER DEFAULT 0,
  streak TEXT,
  conference_rank INTEGER,
  division_rank INTEGER,
  win_pct DOUBLE PRECISION DEFAULT 0,
  games_played INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sync_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  league TEXT NOT NULL,
  status TEXT NOT NULL,
  message TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
